#ifndef INCLUDED_CORE_METAREGISTRATION_H
#define INCLUDED_CORE_METAREGISTRATION_H

#include "Meta.h"

META_TYPE_DECLARE(int)
META_TYPE_DECLARE(float)
META_TYPE_DECLARE(bool)
META_TYPE_DECLARE(std::string)

#endif // !INCLUDED_CORE_METAREGISTRATION_H
